import { ContextProvider } from "@/components/Clients";
import "../styles/app.scss";
import Header from "./Header";
export const metadata = {
  title: "Todo  APP",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>
          <>
            <Header />
            {children}
          </>
        </ContextProvider>
      </body>
    </html>
  );
}
